app/models.py
from . import db
from datetime import datetime
from . import login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
#...

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Pitches(db.Model):

    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(255))
    category = db.Column(db.String(255))
    pitch = db.Column(db.String(255))
    date = db.Column(db.DateTime(250), default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comments', backref='title', lazy='dynamic')

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,cate):
        pitch = Pitches.query.filter_by(category=cate).all()
        return pitch


    def __repr__(self):
        return f"Pitches {self.pitch}','{self.date}')"     


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key=True)
    author = db.Column(db.String(255),index=True)
    email = db.Column(db.String(255),unique=True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pitch = db.relationship('Pitches', backref='author', lazy='dynamic')
    pass_secure = db.Column(db.String(255))
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)
    

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
    

    def __repr__(self):
        return f'User {self.author}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

class Comments(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime(250), default=datetime.utcnow)
    pitches_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))


    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls,id):
        comments = Comments.query.filter_by(pitches_id=id).all()
        return comments

    def __repr__(self):
        return f"Comments('{self.comment}', '{self.date_posted}')"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required
from ..models import User

class PitchForm(FlaskForm):
    title = StringField('Pitch Title')
    category = SelectField(u'Pitch Categories', choices=[('Product', 'Product'), ('Adverts', 'Adverts'),('Interview', 'Interview')])
    pitch = TextAreaField('Pitch')
    submit = SubmitField('Submit')
    
class CommentForm(FlaskForm):
    comment = TextAreaField('Comment')
    submit = SubmitField('Post Comments')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

photos = UploadSet('photos',IMAGES)

simple = SimpleMDE()
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)

    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Will add the views and forms
     # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask_login import login_required, current_user
from flask import render_template,request,redirect,url_for, abort
from ..models import Pitches,Role,User,Comments
from .. import db,photos
from . import main
from ..email import mail_message
from .forms import PitchForm,CommentForm,UpdateProfile

@main.route('/pitch/', methods = ['GET','POST'])
@login_required
def new_pitch():

    form = PitchForm()

    if form.validate_on_submit():
        category = form.category.data
        pitch= form.pitch.data
        title=form.title.data

        # Updated pitchinstance
        new_pitch = Pitches(title=title,category= category,pitch= pitch,user_id=current_user.id)

        title='New Pitch'

        new_pitch.save_pitch()

        return redirect(url_for('main.index'))

    return render_template('pitch.html',form= form)

@main.route('/')
def index():
    '''
    Index page
    return
    '''
    message= "Welcome to Pitch Application!!"
    title= 'Pitch-app!'
    return render_template('index.html', message=message,title=title)


@main.route('/categories/<cate>')
@login_required
def category(cate):
    '''
    function to return the pitches by category
    '''
    category = Pitches.get_pitches(cate)
    # print(category)
    title = f'{cate}'
    return render_template('categories.html',title = title, category = category)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(author = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(author = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.author))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(author = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/comments/<id>')
@login_required
def comment(id):
    '''
    function to return the comments
    '''
    comm =Comments.get_comment(id)
    print(comm)
    title = 'comments'
    return render_template('comments.html',comment = comm,title = title)

@main.route('/new_comment/<int:pitches_id>', methods = ['GET', 'POST'])
@login_required
def new_comment(pitches_id):
    pitches = Pitches.query.filter_by(id = pitches_id).first()
    form = CommentForm()

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comment=comment,user_id=current_user.id, pitches_id=pitches_id)

        new_comment.save_comment()

        return redirect(url_for('main.index'))
    title='New Pitch'
    return render_template('new_comment.html',title=title,comment_form = form,pitches_id=pitches_id)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}
{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

app/templates/categories.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="../static/css/index.css">
{% endblock %}

{% block content %}
<body>  
  <div class="container">
  <br> <hr>   
  <h3 class="text-center">PITCH COMMENTS</h3>
  
    <div class="row">
      <div class="col-md-4"></div>

      <div class="col-md-4" > 
        <div class="card-columns" >
          {% for category in category[::-1] %}

          <div class="card bg-transparent border-success" style="text-align: center;" >
            <div class="card-header bg-transparent border-success">
              {{category.title}}
            </div>
            <div class="card-body text">
                <p>{{category.pitch}}</p><br>
                <footer class="blockquote-footer bg-transparent border-success">{{category.author}}
                  <br><cite title="Source Title">Publish date: {{category.date.strftime('%Y-%m-%d')}}</cite></footer>
            </div>
            <div class="card-footer bg-transparent border-success">
                <button type="button" class="btn btn-outline-success btn-sm"  ><a href="/new_comment/{{category.id}}">Comment</a></button> 
                <button type="button" class="btn btn-outline-success btn-sm" ><a href="/comments/{{category.id}}">View comments</a></button>
              </div>
              <hr> <br>
            </div>
          </div>
        </div>
        
        <div class="col-md-4" style="text-align: center;">
          <script>
var like = 0;

          <button class="social-like" >
            <span class="like"><i class="glyphicon glyphicon-thumbs-up"></i></span>
            <span class="count" >0</span>
        </button>
           &nbsp;
        <button class="social-dislike" >
            <span class="dislike" >0</span>
            <span class="like"><i class="glyphicon glyphicon-thumbs-down"></i></span>
       </button>
      </script>
        </div>
  
      {% endfor %}
      </div>
    </div>
  </body>    
      {% endblock %}

app/templates/comments.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block
styles%} {{ super() }}
<link rel="stylesheet" href="../static/css/index.css" />
{% endblock %} {% block content %}
<body>
  <br /><br />
  <br />
  <div class="container">
    <h3 style="text-align: center;">View New Comments</h3>
    {% for comm in comment[::-1] %}
    <div class="col-sm">
      <div class="well well-lg p-3" id="card" style="text-align: center">
        
        <hr />
        
      <div class="card col-sm mt-2">
        
          <h4 class="card-title">{{comm.author}}</h4>
          <p class="card-text">{{comm.comment}}.</p>
          <div class="card-footer bg-transparent border-success">
            <small
              >Publish date:{{comm.date_posted.strftime('%Y-%m-%d')}}</small
            >
          </div>
          
        </div>
        <br>
        <div style="text-align: center;">
          <button class="social-like" >
            <span class="like"><i class="glyphicon glyphicon-thumbs-up"></i></span>
            <span class="count" >0</span>
        </button>
           &nbsp;
        <button class="social-dislike" >
            <span class="dislike" >0</span>
            <span class="like"><i class="glyphicon glyphicon-thumbs-down"></i></span>
       </button>
      </div>
      </div>
      
    
    </div>
   
      {% endfor %} 
    </div>
  </div>
</body>

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="../static/css/index.css"> 
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->

{% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <h3>WHOOOPS we can't find that page</h1>
</body>
</html>

app/templates/index.html
{% extends 'base.html'%}
{% block styles%} {{ super() }}

<link rel="stylesheet" href="../static/css/index.css"> 
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
  
{% endblock %}

{% block content %}
<div class="jumbotron" style="margin-top:0; background-color: grey;">
  <h2 class="text-center" >PITCH WITH US;</h2>
  <p class="text-center"> Have 60 seconds to impress someone and make something great.!!!</p>
</div> 

<body >

    <div class="container">  
      <div class="col-sm" >
        <div class=" card col-sm mt-2">
          <div class="well well-lg p-3" id="card" style="text-align: center;">
              <h3>Product Pitch</h3>
              <hr>
              <p>Any product that needs a manual to work is broken.</p> </p>
              <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Enter a New Pitch</a></button><br><br>
              <button type="button" class="btn btn-outline-primary"><a href="/categories/Product">Read More</a></button>
          </div>
      </div>
      </div>
      <div class="col-sm">
        <div class=" card col-sm mt-2">
          <div class="well well-lg p-3" id="card" style="text-align: center;">
              <h3>Adverting Pitch</h3>
              <hr>
              <p>“The difference between the almost right word and the right word is the difference between the lightning bug and the lightning.” </p> </p>
              <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Enter a New Pitch</a></button><br><br>
              <button type="button" class="btn btn-outline-primary"><a href="/categories/Adverts">Read More</a></button>
          </div>
      </div>
      </div>

      <div class="col-sm">
        <div class=" card col-sm mt-2">
          <div class="well well-lg p-3" id="card" style="text-align: center;">
              <h3>Iterview Pitches</h3>
              <hr>
              <p>“It’s not whether you get knocked down. It’s whether you get up.”</p> </p>
              <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Enter a New Pitch</a></button><br><br>
              <button type="button" class="btn btn-outline-primary"><a href="/categories/Iterview">Read More</a></button>
          </div>
      </div>
      </div>


    </div>
  
       
  </body>
    <br><br>
    
  <footer class="page-footer font-small pt-4 mt-3 ">
    <div class="container">
    <ul class="list-unstyled list-inline text-center py-2">
        <li class="list-inline-item">
        <h5 class="mb-1">One Minute Pitch</h5>
        </li>
    </ul>
    </div>
    <div class="footer-copyright text-center py-3">
    © 2021 Copyright:
    </div>
</footer>
    {% endblock%}

app/templates/navbar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <link rel="stylesheet" href="../static/css/index.css">
  
  <body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> PITCH HERE! </a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                  <li><a href="/">Home</a></li>
                  <ul class="nav navbar-nav navbar-right">
                      {% if current_user.is_authenticated %}
                      <li><a href="{{url_for('main.profile',uname=current_user.author)}}">Profile</a></li>
                      <li><a href="/">Welcome {{(current_user.author)}}</a></li>
                      <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                      {% else %}
                      <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                      {%endif%}
                    </ul>
          </div>
       </div>
   </div>
</body>
</html>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="../static/css/index.css"> 


{% endblock %}

{% block content %}
<body>

  <div class="container">
    <div class="row">
      <br> <hr> <br>

      <div class="col-md-3"></div>
            
      <div class="col-md-6"> 
        <h3 class="text-center" id="card">LEAVE A COMMENT HERE</h3>
        {{ wtf.quick_form(comment_form) }}
      </div>  
      
      <div class="col-md-3">
        
      </div>
    </div>

  </div>
  

</body>

{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="../static/css/index.css"> 
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->

{% endblock %}

{% block content %}
  <div class="container">
    <div class="row"> 
      <br>
      <h3 class="text-center" >ENTER NEW PITCH HERE</h3>
      <hr> <br>
      <div class="col-md-3"></div>

      <div class="col-md-6">
        {{ wtf.quick_form(form) }}
      </div>

      <div class="col-md-3"></div>
    </div>
  </div>  
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.author| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.author| capitalize}} has no bio </p>
    {% endif %}


    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.author)}}">Edit profile</a>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.author)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>

{% endblock %}